[package]
name = "discord"
version = "0.2.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
clap = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true }
reqwest = { workspace = true }
bytes = { workspace = true }
mime_guess = { workspace = true }
